describe('A few some assertions', function()
    it('Tests positive assertions', function()
        assert.is_true(true)
        assert.True(true)
        assert.are.equal(1, 1)
        assert.has.errors(function()
            error('This should fail.')
        end)
    end)

    it('Tests negative assertions', function()
        assert.is_not_true(false)
        assert.are_not.equals(1, '1')
        assert.has_no.errors(function()
        end)
    end)
end)